VERSION="2.2.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNT="GDAZDU5BLQUWITW6YRYL4XFXXF72ZFVJ2ESGTV2SLO35K6EBEHYH4JED"

[DOCUMENTATION]
ORG_NAME="JetXLM"
ORG_URL="https://jetxlm.github.io"
ORG_LOGO="https://jetxlm.github.io/images/logo.jpg"
ORG_OFFICIAL_EMAIL="jetxlm.com@gmail.com"
ORG_DESCRIPTION="JetXLM stands at the forefront of the digital asset revolution on the Stellar blockchain, offering innovative solutions for asset management and trading. With its commitment to decentralization, user experience, and security, JetXLM is poised to become a leading platform in the blockchain ecosystem."

[[CURRENCIES]]
code="JETXLM"
issuer="GDAZDU5BLQUWITW6YRYL4XFXXF72ZFVJ2ESGTV2SLO35K6EBEHYH4JED"
name="JETXLM"
desc="JETXLM designed to enable efficient and cost-effective cross-border transactions, leveraging the Stellar network's fast processing times and low transaction fees."
image="https://jetxlm.github.io/images/JETXLM.PNG"
conditions="Include Trading Fees"
is_asset_anchored=true
anchor_asset_type="other"
anchor_asset="JETXLM"
display_decimals=7
is_unlimited=true
